spring:
  application:
    name: draw-my-today
  profiles:
    active: local
    include: oauth
  config:
    import:
      - db.yml
      - monitoring.yml


---
spring:
  config:
    activate:
      on-profile: local

---
