spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate.default_batch_fetch_size: 100

---
spring.config.activate.on-profile: local

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/draw_my_today_db?serverTimezone=UTC&characterEncoding=UTF-8
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        #        format_sql: true
        #        show_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

decorator:
  datasource:
    p6spy:
      enable-logging: true

---
spring.config.activate.on-profile: develop

decorator:
  datasource:
    p6spy:
      enable-logging: false